import Navigation from "../components/navigation"
import "../styles/global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <Navigation/>
        {children} {/* 하위 컴포넌트들이 자동으로 전달되는 자리 */}
        &copy; Next JS is great!
      </body>
    </html>
  )
}
